Add nginx-0.48.x-fix
rancher/ingress-nginx pull request #60
Opened 2021-07-15 23:47 UTC by PennyScissors

- Create a new branch`nginx-0.48.x-fix` off of upstream's branch `controller-v0.48.0`
- Cherry-pick commits from `nginx-0.47.x-fix`

2021-07-16 14:31 UTC, superseb approved these changes

2021-07-16 14:33 UTC, superseb requested changes
Did you verify the Golang modules are properly configured when cherry-picking the crypto bump? The GitHub actions security test is failing and complaining about modules.

2021-07-16 20:41 UTC, PennyScissors commented
> Did you verify the Golang modules are properly configured when cherry-picking the crypto bump? The GitHub actions security test is failing and complaining about modules.

Thanks, good catch. I needed to run a go mod tidy.

2021-07-19 14:35 UTC, superseb approved these changes

2021-07-19 19:00 UTC, kinarashah approved these changes

2021-07-19 21:53 UTC, ryansann approved these changes

2021-07-20 17:52 UTC, merged